import path from "node:path";
import { readFile } from "node:fs/promises";
import { collectKnownEnvKeys } from "../readers/dotenv.js";
import type { AnalysisResult, GeneratedFile, GenerateExampleOptions } from "../types.js";

export async function generateExample(result: AnalysisResult, options: GenerateExampleOptions = {}): Promise<GeneratedFile> {
  const filePath = path.join(result.context.root, ".env.example");
  const existingContents = await readExisting(filePath);
  const existing = existingContents.split(/\r?\n/);
  const existingKeys = parseExistingKeys(existing);
  const knownKeys = collectKnownEnvKeys(result.context.envFiles);
  const usageKeys = new Set(result.usages.map((usage) => usage.key));
  const missingKeys = [...new Set([...knownKeys, ...usageKeys])]
    .filter((key) => !existingKeys.includes(key))
    .sort();

  if (existingContents.length > 0) {
    if (missingKeys.length === 0) {
      return {
        path: filePath,
        contents: existingContents,
        changed: false
      };
    }

    const separator = existingContents.endsWith("\n") ? "\n" : "\n\n";
    const additions = ["# Added by EnvDoctor.", ...missingKeys.map((key) => `${key}=`)].join("\n");
    const contents = `${existingContents}${separator}${additions}\n`;

    return {
      path: filePath,
      contents,
      changed: contents !== existingContents
    };
  }

  const lines: string[] = [];

  if (options.includeComments !== false) {
    lines.push("# Generated by EnvDoctor. Fill values locally or in CI secrets.");
    lines.push("");
  }

  lines.push(...missingKeys.map((key) => `${key}=`));

  const contents = `${lines.join("\n")}\n`;
  return {
    path: filePath,
    contents,
    changed: contents !== existingContents
  };
}

async function readExisting(filePath: string): Promise<string> {
  try {
    return await readFile(filePath, "utf8");
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      return "";
    }

    throw error;
  }
}

function parseExistingKeys(lines: string[]): string[] {
  return lines
    .map((line) => line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/)?.[1])
    .filter((key): key is string => Boolean(key));
}
