import path from "node:path";
import { readFile } from "node:fs/promises";
import { collectKnownEnvKeys } from "../readers/dotenv.js";
import type { AnalysisResult, GeneratedFile, GenerateExampleOptions } from "../types.js";

export async function generateExample(result: AnalysisResult, options: GenerateExampleOptions = {}): Promise<GeneratedFile> {
  const filePath = path.join(result.context.root, ".env.example");
  const existing = await readExisting(filePath);
  const existingKeys = parseExistingKeys(existing);
  const knownKeys = collectKnownEnvKeys(result.context.envFiles);
  const usageKeys = new Set(result.usages.map((usage) => usage.key));
  const allKeys = [...new Set([...existingKeys, ...knownKeys, ...usageKeys])].sort();
  const lines: string[] = [];

  if (options.includeComments !== false) {
    lines.push("# Generated by EnvDoctor. Fill values locally or in CI secrets.");
    lines.push("");
  }

  for (const key of allKeys) {
    const existingLine = existing.find((line) => new RegExp(`^\\s*${escapeRegExp(key)}\\s*=`).test(line));
    lines.push(existingLine ?? `${key}=`);
  }

  const contents = `${lines.join("\n")}\n`;
  return {
    path: filePath,
    contents,
    changed: contents !== `${existing.join("\n")}${existing.length > 0 ? "\n" : ""}`
  };
}

async function readExisting(filePath: string): Promise<string[]> {
  try {
    return (await readFile(filePath, "utf8")).split(/\r?\n/).filter((line) => line.length > 0);
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      return [];
    }

    throw error;
  }
}

function parseExistingKeys(lines: string[]): string[] {
  return lines
    .map((line) => line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/)?.[1])
    .filter((key): key is string => Boolean(key));
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
